Imports

In [1]:
import torch
import sys

In [2]:
sys.path.insert(0, '/content/drive/MyDrive/GitHub/TF_API_for_PyTorch')  # if using Google Drive
from api import Model

Sample Usage

In [3]:
class LogisticRegression(Model):

    def __init__(self):
        super().__init__()

        # Layers
        self.Dense = torch.nn.Linear(10, 1)
        self.Sigmoid = torch.nn.Sigmoid()
    
    """
    def build(self):
        # Leave out to use class default.
        # This sets CPU / GPU mode, initializes training progress trackers
        # and placeholder attributes for loss and optimizer
    """

    def forward(self, x, training=False):
        
        # prepare for inference / training
        x = self._forward_prep(x)  # required line
        
        # call
        x = self.Dense(x)
        x = self.Sigmoid(x)

        if training:
            pass
        
        output = x

        return output

    """
    def train_step(self, x, y_true):
        # Custom training logic. 
        # Leave out to use class default.        
        # Class default calls model.forward, computes gradients and updates weights
    """        

    """
    def fit(self, x_data, y_true_data, num_epochs, reporting_freq=1):
        # Custom training loop structure. 
        # Leave out to use class default.
        # Class default calls model.forward, computes gradients and updates weights
    """     

    """
    def compile(self, loss='crossentropy', optimizer_name='adam', callbacks=(),
                loss_kwargs={}, opt_kwargs={}):
        # Loads loss and optimizer. 
        # Leave out to use class default structure.
    """   

In [4]:
batch_size = 20
channels = 10
image_dims = []#[256, 256]
x = 100*torch.rand([batch_size, channels, *image_dims], dtype=torch.float32)
y = torch.ones([batch_size, 1], dtype=torch.float32)

log_reg = LogisticRegression()

#log_reg = log_reg.to(log_reg.device)
log_reg.compile(loss='binary_crossentropy', opt_kwargs={'lr':.001}) 
log_reg(x)

x = x.to(log_reg.device)
#y = y.to(log_reg.device)

log_reg.train_step(x, y)

[Parameter containing:
tensor([[-0.2950, -0.1046,  0.2602, -0.1448,  0.2997, -0.0636, -0.0365,  0.2372,
          0.2734,  0.0877]], requires_grad=True), Parameter containing:
tensor([-0.2853], requires_grad=True)]


2.0708975791931152

In [5]:
train_data = [x], [y]
history = log_reg.fit(*train_data, num_epochs=10000, reporting_freq=1000)

Epoch: 999
epoch loss: 9.196945757139474e-05
Epoch: 1999
epoch loss: 2.8117156034568325e-05
Epoch: 2999
epoch loss: 1.2669855095737148e-05
Epoch: 3999
epoch loss: 6.616346126975259e-06
Epoch: 4999
epoch loss: 3.7134384456294356e-06
Epoch: 5999
epoch loss: 2.169631670767558e-06
Epoch: 6999
epoch loss: 1.293428454118839e-06
Epoch: 7999
epoch loss: 7.867840281505778e-07
Epoch: 8999
epoch loss: 4.768381245412456e-07
Epoch: 9999
epoch loss: 2.9206313456597854e-07


In [6]:
log_reg(x)

tensor([[1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000]], grad_fn=<SigmoidBackward0>)